### ISSUE TITLE
Got an unexpected keyword argument 'proxy_options'

### ISSUE THREAD

**Issue by dheckl** [Azure/azure-iot-sdk-python#590]
- **OS and version used:** Windows 10
- **Python version:** 3.8.2
- **pip version:** <VERSION> (in a command prompt: pip --version )

## Description of the issue

I have installed azure-iot-device 2.1.2 via pip and get following error message after initialization of ProvisioningDeviceClient:

> Got an unexpected keyword argument 'proxy_options'

The validation of the kwargs fails in  azure.iot.device.provisioning.abstract_provisioning_device_client._validate_kwargs because of a missing item "proxy_options" in the whitelist.

## Code sample exhibiting the issue

```
proxy_options = ProxyOptions(proxy_type=socks.SOCKS5, proxy_addr="127.0.0.1", proxy_port=1080, proxy_username="username",
                             proxy_password="password")

provisioning_device_client = ProvisioningDeviceClient.create_from_symmetric_key(
            provisioning_host=provisioning_host,
            registration_id=registration_id,
            id_scope=id_scope,
            symmetric_key=symmetric_key,
            proxy_options=proxy_options
        )
```

## Console log of the issue

> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "\lib\site-packages\azure\iot\device\aio\patch_documentation.py", line 240, in create_from_symmetric_key
>     return super(ProvisioningDeviceClient_, cls).create_from_symmetric_key(
>   File "\lib\site-packages\azure\iot\device\provisioning\abstract_provisioning_device_client.py", line 86, in create_from_symmetric_key
>     _validate_kwargs(**kwargs)
>   File "\lib\site-packages\azure\iot\device\provisioning\abstract_provisioning_device_client.py", line 27, in _validate_kwargs
>     raise TypeError("Got an unexpected keyword argument '{}'".format(kwarg))
> TypeError: Got an unexpected keyword argument 'proxy_options'

AB#7438851

**Comment by olivakar** [comment]
`2.1.2` does not have `proxy_options` for provisioning.
Could you please use the latest version ?

**Comment by dheckl** [comment]
It works with version `2.1.3`. Thank you!

**Comment by az-iot-builder-01** [comment]
@dheckl, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
